image:
  arch: arm64

config:
  clients:
    - url: http://loki-loki-distributed-gateway:80/loki/api/v1/push

  scrape_configs:
    - job_name: springapp
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: springapp
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app
        - replacement: /var/log/pods/*/*/*.log
          target_label: __path__