server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: springboot-app-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: applogs
          app: springboot-app
          __path__: /Users/arunk/Documents/Git/springboot-deploy-flavours/logs/app.log
