apiVersion: v1
kind: Service
metadata:
  name: springapp-service
  labels:
    app: springapp
spec:
  type: LoadBalancer
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 32251
