apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: springapp-run-without-sonar-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: springapp-build-and-push-without-sonar
  params:
    - name: IMAGE
      value: docker.io/akizhaku/springapp:latest
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc2
  serviceAccountName: build-bot