loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: "2025-09-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  limits_config:
    retention_period: 168h

  server:
    http_listen_port: 3100

singleBinary:
  replicas: 1

gateway:
  enabled: true
  replicas: 1
  ingress:
    enabled: false

image:
  arch: arm64