apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: tekton-pipelines
secrets:
  - name: dockerhub-secret
  - name: sonar-auth
  - name: git-credentials
imagePullSecrets:
  - name: dockerhub-secret